Python 


In [ ]:
import math
import numpy as np

In [ ]:
A = np.array([[1,3,2],[5,1,3],[2,1,0]]) #matriz A
A

array([[1, 3, 2],
       [5, 1, 3],
       [2, 1, 0]])

In [ ]:
B = np.array([[1,5,-1],[0,1,1],[3,2,1]]) #matriz B
B

array([[ 1,  5, -1],
       [ 0,  1,  1],
       [ 3,  2,  1]])

In [ ]:
3*A-5*B


array([[ -2, -16,  11],
       [ 15,  -2,   4],
       [ -9,  -7,  -5]])

In [ ]:
A*B #não é a multiplicação que precisamos

array([[ 1, 15, -2],
       [ 0,  1,  3],
       [ 6,  2,  0]])

In [ ]:
A.dot(B) #multiplicação de matrizes A e B.

array([[ 7, 12,  4],
       [14, 32, -1],
       [ 2, 11, -1]])

In [ ]:
B.dot(A) #multiplicação de matrizes B e A.

array([[24,  7, 17],
       [ 7,  2,  3],
       [15, 12, 12]])

In [ ]:
print(A) #Matriz A
print(A.T) #transposta da Matriz A

[[1 3 2]
 [5 1 3]
 [2 1 0]]
[[1 5 2]
 [3 1 1]
 [2 3 0]]


Verificação da Propriedade do Livro

(A.B).T = (B.T).(A.T)

In [ ]:
(A.dot(B)).T


array([[ 7, 14,  2],
       [12, 32, 11],
       [ 4, -1, -1]])

In [ ]:
(B.T).dot(A.T)

array([[ 7, 14,  2],
       [12, 32, 11],
       [ 4, -1, -1]])

Matriz Inversa

In [ ]:
a = np.array([[1,0,2],[1,2,-1],[3,1,5]])
a

array([[ 1,  0,  2],
       [ 1,  2, -1],
       [ 3,  1,  5]])

In [ ]:
ai = np.linalg.inv(a)
ai

array([[11.,  2., -4.],
       [-8., -1.,  3.],
       [-5., -1.,  2.]])

In [ ]:
mult = ai.dot(a)

np.around(mult,5)

array([[ 1.,  0., -0.],
       [-0.,  1.,  0.],
       [-0.,  0.,  1.]])

Determinante

In [ ]:
d=np.linalg.det(a)
d
print(format(d, "5f"))

1.000000


In [ ]:
A = np.array([[-1,-2,-4],[0,-7,11],[3,13,4]])
B = np.array([[2],[-25],[16]])

In [ ]:
np.linalg.inv(A).dot(B)

array([[-2.],
       [ 2.],
       [-1.]])

In [ ]:
A1 = np.array([[1,2,1],[1,-3,5],[2,-1,3]])
B1 = np.array([[12],[1],[10]])

In [ ]:
np.linalg.det(A1)

15.000000000000007

In [ ]:
np.linalg.inv(A1).dot(B1)

array([[5.],
       [3.],
       [1.]])

In [ ]:
A2 = np.array([[-1,2,3],[3,1,1],[1,2,2]])
B2 = np.array([[1],[3],[7]])

In [ ]:
invA2 = np.linalg.inv(A2)

In [ ]:
invA2.dot(B2)

array([[-0.2],
       [10. ],
       [-6.4]])

In [ ]:
A3 = np.array([[3,2,-1],[1,3,1],[2,2,-2]])
B3 = np.array([[0],[1],[2]])

In [ ]:
s3 = np.linalg.inv(A3).dot(B3)
#np.around(s3)
s3

array([[-1.],
       [ 1.],
       [-1.]])

In [ ]:
np.linalg.det(A3)+np.linalg.det(A3.dot(A3))

156.0

In [ ]:
A3**2


array([[ 1,  4,  1],
       [ 1,  1,  0],
       [ 4,  4, 16]])

In [ ]:
A3.dot(A3)

array([[ 1, -2,  5],
       [ 2, -1,  1],
       [12,  6, 18]])

In [ ]:
np.linalg.det(A3)**2

144.0

In [ ]:
A4 = np.array([[1,2,-2],[2,-5,3],[3,4,7]])
d4 = np.linalg.det(A4)
print(format(d4, "5f"))

-103.000000
